Update various tofu modules
moio/dartboard pull request #59
Opened 2024-08-13 01:53 UTC by git-ival

- Adds new inputs for specifying the ssh usernames for different OSes
- Consolidates cluster configuration inputs into 3 vars, 1 for each of upstream, downstream and tester clusters
- Adds an optional aws_profile var for easy usage of different credentials
- Adds additional bastion host-specific input vars

2024-08-13 07:10 UTC, moio requested changes
Please consider the impact on `dart/` files - at least this PR should update the AWS darts according to the different structure you are proposing.

Ideally the other dart-enabled backend (k3d) should be covered - eventually we want all backends to use darts and the same structure.

2024-08-13 07:10 UTC, moio commented on tofu/main/aws/variables.tf
> +    quantity       = number // Number of downstream clusters that should be created using this configuration
Why is `downstream_clusters` a list and then every item of the list has a `quantity` attribute?

I propose to make `downstream_clusters` an object instead of a list, add a separate `downstream_cluster_count` variable and then repeat the downstream configuration `downstream_cluster_count` times in `all_clusters`.

If `downstream_clusters` was a list then the corresponding `dart.yaml` file would need to have the downstream definition repeated many times.

2024-08-13 16:40 UTC, git-ival commented on tofu/main/aws/variables.tf
> +    quantity       = number // Number of downstream clusters that should be created using this configuration
There have been cases where we need to replicate envs which have different downstream clusters with different configurations, so in an attempt to support that I made `downstream_clusters` into a list of objects. I forgot to commit a change to locals.tf which uses the `quantity` attribute in order to build the downstream clusters list appropriately.

We can swap to an object + count var if this is too cumbersome.

2024-08-13 23:40 UTC, git-ival commented on tofu/main/aws/locals.tf
> +  downstream_clusters = [
@moio This was the missing change to handle the `quantity` attribute

2024-08-14 01:46 UTC, git-ival commented on tofu/main/aws/variables.tf
> +    quantity       = number // Number of downstream clusters that should be created using this configuration
If it's decided that we maintain `downstream_clusters` as a list of objects, I can add my modified `aws_full.yaml` dart. Although, it wont be parse-able by dartboard without PR #57 or some other implementation for parsing `[]any` and number types is merged.

2024-08-14 09:06 UTC, moio commented on tofu/main/aws/variables.tf
> +    quantity       = number // Number of downstream clusters that should be created using this configuration
Ooh I see it now. So every item in the `downstream_clusters` list is not the definition of a single downstream cluster, but rather is a definition of a downstream cluster "template" out of which `quantity` homogeneous clusters are created!

So one could define, say, 300 k3s clusters running a certain k3s version, another 200 on another version, 100 on rke2, 100 with bigger hardware and so on...

I am sorry, I completely missed that design idea, and I actually like it a lot. It's brilliant. Thumbs up from my part!

The changes I'd ask are:
 - renaming `downstream_clusters` to `downstream_cluster_groups` or some similar name, to make it evident that each entry is some sort of "template" that is then "repeated" - and that is different from a simple "plural" version `upstream_cluster` or `tester_cluster`
 - to use a name with `count` in it instead of `quantity`, for consistency with the rest of the terminology of the project (I am aware plain `count` is a HCL reserved word)
 - to adapt the included aws dart. We want to have a basic setup that works out of the box

I can take care of adapting the `k3d` and other backends later. Bonus points if you take the time to do that, but that's no obligation for the current PR.

After that feel free to merge.

Thanks for all the work here!

2024-08-14 09:09 UTC, moio approved these changes
Ready to merge as soon as the minor points in https://github.com/moio/dartboard/pull/59#discussion_r1716570864 are done.

Thanks for the collaboration!

2024-08-16 06:02 UTC, merged